### ISSUE TITLE
Text not showing when power activates.

### ISSUE THREAD

**Issue by tmr232** [ambethia/automate-power-mode#1]
When the POWER comes in, all the text disappears.

**Comment by ambethia** [comment]
Are you sure this isn't an issue with the ACTIVATE POWER MODE package? All this package does is toggle that on and off, it shouldn't affect the text buffers at all.

**Comment by tmr232** [comment]
Weird. Now it seems that everything works fine. I must have had some package that killed it, and I can't reproduce it now.
